# Generated by Django 5.2.13 on 2026-04-30 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('inserted', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weekly_hours', models.JSONField(blank=True, default=list)),
                ('weekly_hours_parsed', models.BooleanField(default=False)),
                ('is_24_7', models.BooleanField(default=False)),
                ('accepts_returns', models.BooleanField(default=False)),
                ('accepts_sends', models.BooleanField(default=False)),
                ('payment_available', models.BooleanField(default=False)),
                ('payment_card', models.BooleanField(default=False)),
                ('easy_access', models.BooleanField(default=False)),
                ('physical_type', models.CharField(blank=True, max_length=32)),
                ('neighbors', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='lockers_loc_city_1f05ad_idx'), models.Index(fields=['accepts_returns'], name='lockers_loc_accepts_818b54_idx'), models.Index(fields=['is_24_7'], name='lockers_loc_is_24_7_2e58c7_idx')],
            },
        ),
    ]
