# Generated by Django 5.2.13 on 2026-04-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='location_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
