# Generated by Django 5.2.13 on 2026-05-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_locker_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='payment_available',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='payment_card',
        ),
    ]
