# Generated by Django 5.2.13 on 2026-05-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_remove_locker_name_remove_locker_payment_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngestRun',
        ),
    ]
