# Generated by Django 5.2.13 on 2026-05-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_delete_ingestrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='raw_data',
        ),
    ]
