# Generated by Django 5.2.13 on 2026-05-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0005_remove_locker_raw_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='locker',
            name='lockers_loc_city_1f05ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='locker',
            name='lockers_loc_accepts_818b54_idx',
        ),
        migrations.RemoveIndex(
            model_name='locker',
            name='lockers_loc_is_24_7_2e58c7_idx',
        ),
    ]
