# Generated by Django 5.2.13 on 2026-05-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0006_remove_locker_lockers_loc_city_1f05ad_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='accepts_returns',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='accepts_sends',
        ),
    ]
